const cloudinary = require("cloudinary").v2;
const path = require("path");

module.exports = function(filename) {
   filename = filename.split(".");
  let fileExtension = filename[filename.length - 1];
  filename.pop();
  filename = filename.join(".");

  const eager_options = [
    {
      width: 800,
      crop: "scale",
      format: "jpg"
    }
  ];
  console.log(filename + "." + fileExtension);

  return cloudinary.uploader
    .upload(path.join(__dirname, "../client/public/upload", `${filename}.${fileExtension}`), {
      use_filename: true,
      eager: eager_options,
      public_id: filename
    })
    .then(function(image, err) {
      console.log("upload");
      console.log(
        "* public_id for the uploaded image is generated by Cloudinary's service."
      );
      console.log("* " + image.public_id);
      console.log("* " + image.url);
      console.log(image);
      return image.eager[0].secure_url;
    })
    .catch(function(err) {
      if (err) {
        console.warn(err);
      }
    });
};
